# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectObjects.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setGeometry(QtCore.QRect(310, 260, 151, 28))
        self.openButton.setObjectName("openButton")
        self.resButton = QtWidgets.QPushButton(self.centralwidget)
        self.resButton.setEnabled(False)
        self.resButton.setGeometry(QtCore.QRect(310, 300, 151, 28))
        self.resButton.setObjectName("resButton")
        self.optionBox = QtWidgets.QGroupBox(self.centralwidget)
        self.optionBox.setGeometry(QtCore.QRect(10, 240, 271, 171))
        self.optionBox.setObjectName("optionBox")
        self.name_checkBox = QtWidgets.QCheckBox(self.optionBox)
        self.name_checkBox.setGeometry(QtCore.QRect(20, 20, 221, 20))
        self.name_checkBox.setObjectName("name_checkBox")
        self.prob_checkBox = QtWidgets.QCheckBox(self.optionBox)
        self.prob_checkBox.setGeometry(QtCore.QRect(20, 50, 241, 20))
        self.prob_checkBox.setObjectName("prob_checkBox")
        self.minProb_text = QtWidgets.QTextEdit(self.optionBox)
        self.minProb_text.setGeometry(QtCore.QRect(20, 80, 41, 31))
        self.minProb_text.setObjectName("minProb_text")
        self.label = QtWidgets.QLabel(self.optionBox)
        self.label.setGeometry(QtCore.QRect(70, 80, 191, 16))
        self.label.setObjectName("label")
        self.fps_text = QtWidgets.QTextEdit(self.optionBox)
        self.fps_text.setEnabled(False)
        self.fps_text.setGeometry(QtCore.QRect(20, 120, 41, 31))
        self.fps_text.setObjectName("fps_text")
        self.label_2 = QtWidgets.QLabel(self.optionBox)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 201, 16))
        self.label_2.setObjectName("label_2")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 10, 261, 192))
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.sourceButton = QtWidgets.QPushButton(self.centralwidget)
        self.sourceButton.setEnabled(False)
        self.sourceButton.setGeometry(QtCore.QRect(480, 300, 151, 28))
        self.sourceButton.setObjectName("sourceButton")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(False)
        self.startButton.setGeometry(QtCore.QRect(480, 260, 151, 28))
        self.startButton.setObjectName("startButton")
        self.editPhotoButton = QtWidgets.QPushButton(self.centralwidget)
        self.editPhotoButton.setEnabled(False)
        self.editPhotoButton.setGeometry(QtCore.QRect(310, 340, 321, 31))
        self.editPhotoButton.setObjectName("editPhotoButton")
        self.crapResult_label = QtWidgets.QLabel(self.centralwidget)
        self.crapResult_label.setGeometry(QtCore.QRect(320, 20, 291, 171))
        self.crapResult_label.setText("")
        self.crapResult_label.setObjectName("crapResult_label")
        self.original_photo = QtWidgets.QPushButton(self.centralwidget)
        self.original_photo.setEnabled(False)
        self.original_photo.setGeometry(QtCore.QRect(310, 380, 321, 31))
        self.original_photo.setObjectName("original_photo")
        self.settings_button = QtWidgets.QPushButton(self.centralwidget)
        self.settings_button.setEnabled(False)
        self.settings_button.setGeometry(QtCore.QRect(310, 420, 321, 51))
        self.settings_button.setObjectName("settings_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 22))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionWebcam = QtWidgets.QAction(MainWindow)
        self.actionWebcam.setCheckable(False)
        self.actionWebcam.setChecked(False)
        self.actionWebcam.setObjectName("actionWebcam")
        self.actionwebcam_test = QtWidgets.QAction(MainWindow)
        self.actionwebcam_test.setObjectName("actionwebcam_test")
        self.action_objectSet = QtWidgets.QAction(MainWindow)
        self.action_objectSet.setObjectName("action_objectSet")
        self.menuExit.addAction(self.actionWebcam)
        self.menuExit.addAction(self.actionwebcam_test)
        self.menuExit.addAction(self.action_objectSet)
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openButton.setText(_translate("MainWindow", "Загрузить файл"))
        self.resButton.setText(_translate("MainWindow", "Результат"))
        self.optionBox.setTitle(_translate("MainWindow", "Опции:"))
        self.name_checkBox.setText(_translate("MainWindow", "Отобразить названия объектов"))
        self.prob_checkBox.setText(_translate("MainWindow", "Отобразить точность"))
        self.label.setText(_translate("MainWindow", "Минимальная точность"))
        self.label_2.setText(_translate("MainWindow", "Кадров в секунду(только видео)"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Объекты"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Количество"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Номер кадра"))
        self.sourceButton.setText(_translate("MainWindow", "Исходный файл"))
        self.startButton.setText(_translate("MainWindow", "Запуск"))
        self.editPhotoButton.setText(_translate("MainWindow", "Обрезка/масштаб фотографии"))
        self.original_photo.setText(_translate("MainWindow", "Вернуть первоначальное фото"))
        self.settings_button.setText(_translate("MainWindow", "Открыть настройки изображения"))
        self.menuExit.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionWebcam.setText(_translate("MainWindow", "Webcam"))
        self.actionwebcam_test.setText(_translate("MainWindow", "webcam(test, not RT)"))
        self.action_objectSet.setText(_translate("MainWindow", "Настроить отображение объектов"))

